### ISSUE TITLE
How can I implement the alg?

### ISSUE THREAD

**Issue by tristanwhh** [willscott/rappor#6]
How can I implement the alg? I don't know how to implement the alg no matter in an extension format or with a broswer console... Can you help me?
Can you leave your contact info, like email msg, Whatsapp, signal, facebook, telegram or something else to help me?
I spend much time on it, but I still cannot do so...
Thank you...

**Comment by willscott** [comment]
I'm afraid I don't have the time to help. I can only recommend referring back to the original implementation and paper linked in the readme.
